name: Builds and pushes backend Docker image to Docker Hub
on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/workflows/backend_docker.yml
  workflow_dispatch:
    inputs:
      branch:
        description: Also deploy?
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inv-manager-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/inv-manager-backend:${{ github.sha }}
